[[bin]]
name = "client"
path = "src/bin/client.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[package]
name = "snmp_t"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.4.0"
anyhow = "1.0.65"